/*
 * Copyright (C) 2006 Registro.br. All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without 
 * modification, are permitted provided that the following conditions are 
 * met: 
 * 1. Redistribution of source code must retain the above copyright 
 *    notice, this list of conditions and the following disclaimer. 
 * 2. Redistributions in binary form must reproduce the above copyright 
 *    notice, this list of conditions and the following disclaimer in the 
 *    documentation and\/or other materials provided with the distribution. 
 *  
 * THIS SOFTWARE IS PROVIDED BY REGISTRO.BR AS IS'' AND ANY EXPRESS OR 
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
 * WARRANTIE OF FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO 
 * EVENT SHALL REGISTRO.BR BE LIABLE FOR ANY DIRECT, INDIRECT, 
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS 
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND 
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR 
 * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE 
 * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH 
 * DAMAGE. 
 */
/** @file libepp_nicbr.H
 *  @brief Project defines
 */

#ifndef __LIBEPP_NICBR_H__
#define __LIBEPP_NICBR_H__

#define LIBEPP_NICBR_NS_BEGIN namespace libepp_nicbr {
#define LIBEPP_NICBR_NS_END }
#define LIBEPP_NICBR_NS_USE using namespace libepp_nicbr;

#define SCHEMASDIR "/usr/local/share/libepp_nicbr/schemas"
#define TEMPLATESDIR "/usr/local/share/libepp_nicbr/templates"
#define SSLCERTDIR "/usr/local/share/libepp_nicbr/ssl"

#endif //__LIBEPP_NICBR_H__
